// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBskfQKAKN4hCWWP2xxbXQM8dCVHib73wk',
    appId: '1:920799751619:web:8e58e79030eedb5b816176',
    messagingSenderId: '920799751619',
    projectId: 'my-plant-app-001',
    authDomain: 'my-plant-app-001.firebaseapp.com',
    storageBucket: 'my-plant-app-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXKUTlXILRl9gc-3gv0Muxop4P0LXwR4',
    appId: '1:920799751619:android:99e2c35e3dc41d89816176',
    messagingSenderId: '920799751619',
    projectId: 'my-plant-app-001',
    storageBucket: 'my-plant-app-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVuKjiOVqURbhA5nOVyDKnEZ5YpMmOts',
    appId: '1:920799751619:ios:b48e23fbbba267cb816176',
    messagingSenderId: '920799751619',
    projectId: 'my-plant-app-001',
    storageBucket: 'my-plant-app-001.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVuKjiOVqURbhA5nOVyDKnEZ5YpMmOts',
    appId: '1:920799751619:ios:b48e23fbbba267cb816176',
    messagingSenderId: '920799751619',
    projectId: 'my-plant-app-001',
    storageBucket: 'my-plant-app-001.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBskfQKAKN4hCWWP2xxbXQM8dCVHib73wk',
    appId: '1:920799751619:web:bb132a9aed36ea8d816176',
    messagingSenderId: '920799751619',
    projectId: 'my-plant-app-001',
    authDomain: 'my-plant-app-001.firebaseapp.com',
    storageBucket: 'my-plant-app-001.appspot.com',
  );
}
