// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIx3cEXuBROTsUv_beBDNoCWhrNflFRNg',
    appId: '1:645120312493:web:f851b309386cdd799ef224',
    messagingSenderId: '645120312493',
    projectId: 'my-instagram-app-45e4f',
    authDomain: 'my-instagram-app-45e4f.firebaseapp.com',
    storageBucket: 'my-instagram-app-45e4f.appspot.com',
    measurementId: 'G-PWR73HGZHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDuku3Ph_Mvz_8oiZ7rJGbFILizWthIM',
    appId: '1:645120312493:android:826a464decb128049ef224',
    messagingSenderId: '645120312493',
    projectId: 'my-instagram-app-45e4f',
    storageBucket: 'my-instagram-app-45e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eGleKei3QNE_cDnDz-g_bllLahBSo_o',
    appId: '1:645120312493:ios:aa33d6368799a95e9ef224',
    messagingSenderId: '645120312493',
    projectId: 'my-instagram-app-45e4f',
    storageBucket: 'my-instagram-app-45e4f.appspot.com',
    androidClientId: '645120312493-ogqhv69k2ibjkslnj2oqgc0nomteglcj.apps.googleusercontent.com',
    iosClientId: '645120312493-89ad11r8qi6ublgp25tp3m49civp8me2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eGleKei3QNE_cDnDz-g_bllLahBSo_o',
    appId: '1:645120312493:ios:aa33d6368799a95e9ef224',
    messagingSenderId: '645120312493',
    projectId: 'my-instagram-app-45e4f',
    storageBucket: 'my-instagram-app-45e4f.appspot.com',
    androidClientId: '645120312493-ogqhv69k2ibjkslnj2oqgc0nomteglcj.apps.googleusercontent.com',
    iosClientId: '645120312493-89ad11r8qi6ublgp25tp3m49civp8me2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramUi',
  );

}